/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DashboardTestRouteImport } from './routes/dashboard/test'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DashboardProjectProjectIdRouteImport } from './routes/dashboard/project.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project.$projectId/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DashboardProjectProjectIdTypesRouteImport } from './routes/dashboard/project.$projectId/types'
import { Route as DashboardProjectProjectIdOperationsRouteImport } from './routes/dashboard/project.$projectId/operations'
import { Route as DashboardProjectProjectIdLocationsRouteImport } from './routes/dashboard/project.$projectId/locations'
import { Route as DashboardProjectProjectIdFieldsRouteImport } from './routes/dashboard/project.$projectId/fields'
import { Route as DashboardProjectProjectIdErrorsRouteImport } from './routes/dashboard/project.$projectId/errors'
import { Route as DashboardProjectProjectIdClientsRouteImport } from './routes/dashboard/project.$projectId/clients'
import { Route as DashboardProjectProjectIdApiKeysRouteImport } from './routes/dashboard/project.$projectId/api-keys'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestRoute = DashboardTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdRoute =
  DashboardProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdTypesRoute =
  DashboardProjectProjectIdTypesRouteImport.update({
    id: '/types',
    path: '/types',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdOperationsRoute =
  DashboardProjectProjectIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdLocationsRoute =
  DashboardProjectProjectIdLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdFieldsRoute =
  DashboardProjectProjectIdFieldsRouteImport.update({
    id: '/fields',
    path: '/fields',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdErrorsRoute =
  DashboardProjectProjectIdErrorsRouteImport.update({
    id: '/errors',
    path: '/errors',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdClientsRoute =
  DashboardProjectProjectIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdApiKeysRoute =
  DashboardProjectProjectIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/project/$projectId/api-keys': typeof DashboardProjectProjectIdApiKeysRoute
  '/dashboard/project/$projectId/clients': typeof DashboardProjectProjectIdClientsRoute
  '/dashboard/project/$projectId/errors': typeof DashboardProjectProjectIdErrorsRoute
  '/dashboard/project/$projectId/fields': typeof DashboardProjectProjectIdFieldsRoute
  '/dashboard/project/$projectId/locations': typeof DashboardProjectProjectIdLocationsRoute
  '/dashboard/project/$projectId/operations': typeof DashboardProjectProjectIdOperationsRoute
  '/dashboard/project/$projectId/types': typeof DashboardProjectProjectIdTypesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/project/$projectId/api-keys': typeof DashboardProjectProjectIdApiKeysRoute
  '/dashboard/project/$projectId/clients': typeof DashboardProjectProjectIdClientsRoute
  '/dashboard/project/$projectId/errors': typeof DashboardProjectProjectIdErrorsRoute
  '/dashboard/project/$projectId/fields': typeof DashboardProjectProjectIdFieldsRoute
  '/dashboard/project/$projectId/locations': typeof DashboardProjectProjectIdLocationsRoute
  '/dashboard/project/$projectId/operations': typeof DashboardProjectProjectIdOperationsRoute
  '/dashboard/project/$projectId/types': typeof DashboardProjectProjectIdTypesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/project/$projectId/api-keys': typeof DashboardProjectProjectIdApiKeysRoute
  '/dashboard/project/$projectId/clients': typeof DashboardProjectProjectIdClientsRoute
  '/dashboard/project/$projectId/errors': typeof DashboardProjectProjectIdErrorsRoute
  '/dashboard/project/$projectId/fields': typeof DashboardProjectProjectIdFieldsRoute
  '/dashboard/project/$projectId/locations': typeof DashboardProjectProjectIdLocationsRoute
  '/dashboard/project/$projectId/operations': typeof DashboardProjectProjectIdOperationsRoute
  '/dashboard/project/$projectId/types': typeof DashboardProjectProjectIdTypesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/dashboard/test'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/project/$projectId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/project/$projectId/api-keys'
    | '/dashboard/project/$projectId/clients'
    | '/dashboard/project/$projectId/errors'
    | '/dashboard/project/$projectId/fields'
    | '/dashboard/project/$projectId/locations'
    | '/dashboard/project/$projectId/operations'
    | '/dashboard/project/$projectId/types'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/project/$projectId/'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/dashboard/test'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/project/$projectId/api-keys'
    | '/dashboard/project/$projectId/clients'
    | '/dashboard/project/$projectId/errors'
    | '/dashboard/project/$projectId/fields'
    | '/dashboard/project/$projectId/locations'
    | '/dashboard/project/$projectId/operations'
    | '/dashboard/project/$projectId/types'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/project/$projectId'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/dashboard/test'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/project/$projectId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/project/$projectId/api-keys'
    | '/dashboard/project/$projectId/clients'
    | '/dashboard/project/$projectId/errors'
    | '/dashboard/project/$projectId/fields'
    | '/dashboard/project/$projectId/locations'
    | '/dashboard/project/$projectId/operations'
    | '/dashboard/project/$projectId/types'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/project/$projectId/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/test': {
      id: '/dashboard/test'
      path: '/test'
      fullPath: '/dashboard/test'
      preLoaderRoute: typeof DashboardTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId': {
      id: '/dashboard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/types': {
      id: '/dashboard/project/$projectId/types'
      path: '/types'
      fullPath: '/dashboard/project/$projectId/types'
      preLoaderRoute: typeof DashboardProjectProjectIdTypesRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/operations': {
      id: '/dashboard/project/$projectId/operations'
      path: '/operations'
      fullPath: '/dashboard/project/$projectId/operations'
      preLoaderRoute: typeof DashboardProjectProjectIdOperationsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/locations': {
      id: '/dashboard/project/$projectId/locations'
      path: '/locations'
      fullPath: '/dashboard/project/$projectId/locations'
      preLoaderRoute: typeof DashboardProjectProjectIdLocationsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/fields': {
      id: '/dashboard/project/$projectId/fields'
      path: '/fields'
      fullPath: '/dashboard/project/$projectId/fields'
      preLoaderRoute: typeof DashboardProjectProjectIdFieldsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/errors': {
      id: '/dashboard/project/$projectId/errors'
      path: '/errors'
      fullPath: '/dashboard/project/$projectId/errors'
      preLoaderRoute: typeof DashboardProjectProjectIdErrorsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/clients': {
      id: '/dashboard/project/$projectId/clients'
      path: '/clients'
      fullPath: '/dashboard/project/$projectId/clients'
      preLoaderRoute: typeof DashboardProjectProjectIdClientsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/api-keys': {
      id: '/dashboard/project/$projectId/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/project/$projectId/api-keys'
      preLoaderRoute: typeof DashboardProjectProjectIdApiKeysRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
  }
}

interface DashboardProjectProjectIdRouteChildren {
  DashboardProjectProjectIdApiKeysRoute: typeof DashboardProjectProjectIdApiKeysRoute
  DashboardProjectProjectIdClientsRoute: typeof DashboardProjectProjectIdClientsRoute
  DashboardProjectProjectIdErrorsRoute: typeof DashboardProjectProjectIdErrorsRoute
  DashboardProjectProjectIdFieldsRoute: typeof DashboardProjectProjectIdFieldsRoute
  DashboardProjectProjectIdLocationsRoute: typeof DashboardProjectProjectIdLocationsRoute
  DashboardProjectProjectIdOperationsRoute: typeof DashboardProjectProjectIdOperationsRoute
  DashboardProjectProjectIdTypesRoute: typeof DashboardProjectProjectIdTypesRoute
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
}

const DashboardProjectProjectIdRouteChildren: DashboardProjectProjectIdRouteChildren =
  {
    DashboardProjectProjectIdApiKeysRoute:
      DashboardProjectProjectIdApiKeysRoute,
    DashboardProjectProjectIdClientsRoute:
      DashboardProjectProjectIdClientsRoute,
    DashboardProjectProjectIdErrorsRoute: DashboardProjectProjectIdErrorsRoute,
    DashboardProjectProjectIdFieldsRoute: DashboardProjectProjectIdFieldsRoute,
    DashboardProjectProjectIdLocationsRoute:
      DashboardProjectProjectIdLocationsRoute,
    DashboardProjectProjectIdOperationsRoute:
      DashboardProjectProjectIdOperationsRoute,
    DashboardProjectProjectIdTypesRoute: DashboardProjectProjectIdTypesRoute,
    DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
  }

const DashboardProjectProjectIdRouteWithChildren =
  DashboardProjectProjectIdRoute._addFileChildren(
    DashboardProjectProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardTestRoute: typeof DashboardTestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdRoute: typeof DashboardProjectProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTestRoute: DashboardTestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdRoute: DashboardProjectProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
