import {
	films,
	getByTypeId,
	getByUrl,
	getId,
	people,
	planets,
	resolveMany,
	type SwapiRecord,
	species,
	starships,
	toFloat,
	toInt,
	vehicles,
} from "./data";

type IdArgs = { id: string };

export const resolvers = {
	Query: {
		allFilms: () => films,
		allPeople: () => people,
		allPlanets: () => planets,
		allSpecies: () => species,
		allStarships: () => starships,
		allVehicles: () => vehicles,
		film: (_: unknown, { id }: IdArgs) => getByTypeId("films", id),
		person: (_: unknown, { id }: IdArgs) => getByTypeId("people", id),
		planet: (_: unknown, { id }: IdArgs) => getByTypeId("planets", id),
		species: (_: unknown, { id }: IdArgs) => getByTypeId("species", id),
		starship: (_: unknown, { id }: IdArgs) => getByTypeId("starships", id),
		vehicle: (_: unknown, { id }: IdArgs) => getByTypeId("vehicles", id),
	},
	Film: {
		id: (film: SwapiRecord) => getId(film.url),
		episodeId: (film: SwapiRecord) => toInt(film.episode_id),
		openingCrawl: (film: SwapiRecord) => film.opening_crawl,
		releaseDate: (film: SwapiRecord) => film.release_date,
		species: (film: SwapiRecord) => resolveMany(film.species),
		starships: (film: SwapiRecord) => resolveMany(film.starships),
		vehicles: (film: SwapiRecord) => resolveMany(film.vehicles),
		characters: (film: SwapiRecord) => resolveMany(film.characters),
		planets: (film: SwapiRecord) => resolveMany(film.planets),
	},
	Person: {
		id: (person: SwapiRecord) => getId(person.url),
		birthYear: (person: SwapiRecord) => person.birth_year,
		eyeColor: (person: SwapiRecord) => person.eye_color,
		hairColor: (person: SwapiRecord) => person.hair_color,
		skinColor: (person: SwapiRecord) => person.skin_color,
		height: (person: SwapiRecord) => toInt(person.height),
		mass: (person: SwapiRecord) => toFloat(person.mass),
		homeworld: (person: SwapiRecord) => getByUrl(person.homeworld),
		films: (person: SwapiRecord) => resolveMany(person.films),
		species: (person: SwapiRecord) => resolveMany(person.species),
		starships: (person: SwapiRecord) => resolveMany(person.starships),
		vehicles: (person: SwapiRecord) => resolveMany(person.vehicles),
	},
	Planet: {
		id: (planet: SwapiRecord) => getId(planet.url),
		diameter: (planet: SwapiRecord) => toInt(planet.diameter),
		rotationPeriod: (planet: SwapiRecord) => toInt(planet.rotation_period),
		orbitalPeriod: (planet: SwapiRecord) => toInt(planet.orbital_period),
		gravity: (planet: SwapiRecord) => planet.gravity,
		population: (planet: SwapiRecord) => toFloat(planet.population),
		climate: (planet: SwapiRecord) => planet.climate,
		terrain: (planet: SwapiRecord) => planet.terrain,
		surfaceWater: (planet: SwapiRecord) => toFloat(planet.surface_water),
		residents: (planet: SwapiRecord) => resolveMany(planet.residents),
		films: (planet: SwapiRecord) => resolveMany(planet.films),
	},
	Species: {
		id: (species: SwapiRecord) => getId(species.url),
		classification: (species: SwapiRecord) => species.classification,
		designation: (species: SwapiRecord) => species.designation,
		averageHeight: (species: SwapiRecord) => toInt(species.average_height),
		averageLifespan: (species: SwapiRecord) => toInt(species.average_lifespan),
		eyeColors: (species: SwapiRecord) => species.eye_colors,
		hairColors: (species: SwapiRecord) => species.hair_colors,
		skinColors: (species: SwapiRecord) => species.skin_colors,
		language: (species: SwapiRecord) => species.language,
		homeworld: (species: SwapiRecord) => getByUrl(species.homeworld),
		people: (species: SwapiRecord) => resolveMany(species.people),
		films: (species: SwapiRecord) => resolveMany(species.films),
	},
	Starship: {
		id: (starship: SwapiRecord) => getId(starship.url),
		model: (starship: SwapiRecord) => starship.model,
		manufacturer: (starship: SwapiRecord) => starship.manufacturer,
		costInCredits: (starship: SwapiRecord) => toFloat(starship.cost_in_credits),
		length: (starship: SwapiRecord) => toFloat(starship.length),
		maxAtmospheringSpeed: (starship: SwapiRecord) =>
			toInt(starship.max_atmosphering_speed),
		crew: (starship: SwapiRecord) => toInt(starship.crew),
		passengers: (starship: SwapiRecord) => toInt(starship.passengers),
		cargoCapacity: (starship: SwapiRecord) => toFloat(starship.cargo_capacity),
		consumables: (starship: SwapiRecord) => starship.consumables,
		hyperdriveRating: (starship: SwapiRecord) =>
			toFloat(starship.hyperdrive_rating),
		mglt: (starship: SwapiRecord) => toInt(starship.MGLT),
		starshipClass: (starship: SwapiRecord) => starship.starship_class,
		pilots: (starship: SwapiRecord) => resolveMany(starship.pilots),
		films: (starship: SwapiRecord) => resolveMany(starship.films),
	},
	Vehicle: {
		id: (vehicle: SwapiRecord) => getId(vehicle.url),
		model: (vehicle: SwapiRecord) => vehicle.model,
		manufacturer: (vehicle: SwapiRecord) => vehicle.manufacturer,
		costInCredits: (vehicle: SwapiRecord) => toFloat(vehicle.cost_in_credits),
		length: (vehicle: SwapiRecord) => toFloat(vehicle.length),
		maxAtmospheringSpeed: (vehicle: SwapiRecord) =>
			toInt(vehicle.max_atmosphering_speed),
		crew: (vehicle: SwapiRecord) => toInt(vehicle.crew),
		passengers: (vehicle: SwapiRecord) => toInt(vehicle.passengers),
		cargoCapacity: (vehicle: SwapiRecord) => toFloat(vehicle.cargo_capacity),
		consumables: (vehicle: SwapiRecord) => vehicle.consumables,
		vehicleClass: (vehicle: SwapiRecord) => vehicle.vehicle_class,
		pilots: (vehicle: SwapiRecord) => resolveMany(vehicle.pilots),
		films: (vehicle: SwapiRecord) => resolveMany(vehicle.films),
	},
};
